# # version: ‘3’
services:
  web:
   container_name: django-docker
   build: .
   command: python3 manage.py runserver 0.0.0.0:8000
   working_dir: /code
   ports:
    - "8000:8000"
   volumes:
     - .:/code
   depends_on:
     - db
  db:
   image: postgres
   restart: always
   environment:
      POSTGRES_PASSWORD: password
      # POSTGRES_DB: "db"
      # POSTGRES_HOST_AUTH_METHOD: "trust"